apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmlglx-root-vol
  namespace: ucsd-digital-media-lab
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
