apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xrxgl-sw-vol
  namespace: librareome
spec:
  storageClassName: seaweedfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1T
