apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xrxgl-cache-vol
  namespace: librareome
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
